### ISSUE TITLE
Update validation errors

### ISSUE THREAD

**Issue by JohanLarsson** [JohanLarsson/Gu.Wpf.NumericInput#22]
WPF does not update validation errors if there already is an error.
Say we have < 5 rule and violate that with [6]
If we then type in [6abc] it should be updated to 'can't parse' but keeps the 'greater than' error.

Here is a screenie of vanilla TextBox:

![screenie](http://i.imgur.com/EgX3ozX.gif)

**Comment by JohanLarsson** [comment]
Soved by dk.

**Comment by ondrasvoboda** [comment]
Hi, 
may I ask you how did you solved this issue?
I'm facing the same and another similar:

- I have RequiredAttribute in VM
- when I enter some invalid number [gg] I still get [field is required] error, I would expect [invalid number] error

(I'm using INotifyDataErrorInfo)

**Comment by ondrasvoboda** [comment]
Unfortunately not.
I don't know how to mix validation errors from NumericInput with my validation in view model implementing INotifyDataErrorInfo.

**Comment by JohanLarsson** [comment]
Maybe there is a bug, we should try to put together a minimal repro. If you have time you can write a PR and add it as a window [here](https://github.com/GuOrg/Gu.Wpf.NumericInput/tree/master/Gu.Wpf.NumericInput.Demo/Windows)

Then we can use it in UI-tests if you found a bug. Alternatively create a repository with a minimal application showing the bug.

**Comment by JohanLarsson** [comment]
It works with `INotifyDataErrorInfo`, there are UI-tests for it. Not saying it works in your specific use case. You can clone the repo and check out the demo app.
