### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by ondrasvoboda** [JohanLarsson/Gu.Wpf.NumericInput#29]
Hi,
I'm developing a multilingual app and will need to localize your great tool to more languages.
Do you need to always create resource file for new language or is there a way how can I provide localized texts from my app (maybe some localization provider interface I don't see)?
Thank you!
Ondra

**Comment by JohanLarsson** [comment]
If you don't need custom messages you can make pull requests with missing languages and I'll update the nuget.

The validation results are [typed](https://github.com/JohanLarsson/Gu.Wpf.NumericInput/tree/master/Gu.Wpf.NumericInput/Validation/ValidationResults) so you should be able to use data templates if you have custom needs.

**Comment by ondrasvoboda** [comment]
OK, thanks.

**Comment by JohanLarsson** [comment]
Did it solve your problem?

**Comment by ondrasvoboda** [comment]
Yes, I will create pull requests for missing languages.

**Comment by JohanLarsson** [comment]
https://www.visualstudiogallery.msdn.microsoft.com/3b64e04c-e8de-4b97-8358-06c73a97cc68

^ is nice for managing resource files.
