### ISSUE TITLE
Enable spinners to update binding when LostFocus .

### ISSUE THREAD

**Issue by JohanLarsson** [JohanLarsson/Gu.Wpf.NumericInput#31]
Most of the time a `NumericBox` will be bound with `UpdateSourceTrigger = UpdateSourceTrigger .LostFocus` and this is also the default for the `Value` dependency property.

When updating the value using for example the spinner buttons there is no validation issue so it can be nice UX to send the updated value to the viewmodel with `PropertyChanged` even if the box is bound with `LostFocus`

Question is what to name things.

```c#
/// <summary>
/// Controls how the increment and decrement commands work.
/// </summary>
public enum SpinMode
{
    /// <summary>
    /// Use the same as the binding i.e. LostFocus or PropertyChanged
    /// </summary>
    AsBinding,

    /// <summary>
    /// Update the binding on click.
    /// </summary>
    Update
}
```

**Comment by ReedCopsey** [comment]
I'd do something like

```csharp
enum SpinUpdateMode
{
    MimickValueBinding,
    LostFocus,
    PropertyChanged
}```
